import { writable } from 'svelte/store';

const seniorsStore = writable([
  'Saachika Agashe',
  'Tito Aguirre',
  'Deeksha Bahl',
  'Vaibhav Balakrishnan',
  'Eggs Batarla',
  'Ayden Bell',
  'Umar Bhatti',
  'Aneesh Chavda',
  'Sankalp Chillarige',
  'Josh Choi',
  'Atley Fegan',
  'Jackson Franzen',
  'Denize Hazrati',
  'Loyd Jacoby',
  'Abby Keenan',
  'Aryan Khanal',
  'Grant Kleinsmith',
  'Zach McDonald',
  'Emil Mendoza Garcia',
  'Nicholas Mueller',
  'Camden Ogura',
  'Drew Olivieri',
  'Sunny Panthangi',
  'Medha Pathuri',
  'Abby Ramesh',
  'Caitlyn Roldan',
  'Santi Romero Florero',
  'Monisha Satish',
  'Archana Shankar',
  'Michael Sheffler',
  'Thomas Sherrick',
  'Oliver Tam',
  'Rachel Tobias',
  'Chelsea Van Baah',
  'Rebecca Weathington',
  'Emmi Wickersham',
  'Ben Wu',
  'Imogen Yabes'
]);

export default seniorsStore;
