name: Build SvelteKit App

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0 # Action to check out your code

      - name: Setup Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22' # Specify the Node.js version

      - name: Install dependencies
        run: npm install # Install project dependencies

      - name: Build SvelteKit app
        run: npm run build # Run the build command defined in your package.json
